name: Update Article Links

on:
  schedule:
    - cron: '0 0 * * *'  # 每天執行
  workflow_dispatch:      # 也可手動觸發

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v3
        with:
          path: website
          
      - name: Checkout articles repo  
        uses: actions/checkout@v3
        with:
          repository: myyang19770915/SingleFile-Archives
          path: articles
          
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Update links
        run: |
          python update-links.py
          
      - name: Commit changes
        run: |
          cd website
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit -m "Update article links"
          git push
